spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://CKDEVELOPER:1433;databaseName=ContactDB;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.servlet.context-path=/api/v1

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

cors.allowed-origins=http://localhost:5173,http://localhost:3000

logging.level.com.cms=DEBUG
logging.file.name=logs/cms-application.log